"""Add Goal model

Revision ID: 974cba1ca96a
Revises: 
Create Date: 2025-02-03 18:08:51.629304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974cba1ca96a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('works_well', sa.Text(), nullable=True),
    sa.Column('needs_change', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_tasks',
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_tasks')
    op.drop_table('goal')
    # ### end Alembic commands ###
