"""Add must_do field to Goal model

Revision ID: a94a56e4173d
Revises: 974cba1ca96a
Create Date: 2025-02-03 18:21:10.777561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a94a56e4173d'
down_revision = '974cba1ca96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_do', sa.Text(), nullable=True))
        batch_op.alter_column('objectives',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('objectives',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.drop_column('must_do')

    # ### end Alembic commands ###
